{
 "title": "fraud_sql",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Merchant Fraud Exposure",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT merchant, SUM(amount) \r\nFROM transaction_predictions \r\nWHERE prediction = 1\r\nGROUP BY merchant;\r\n"
    }
   ]
  },
  {
   "title": "Fraud Transaction",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT * FROM transaction_predictions WHERE prediction = 1;"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT *\r\nFROM (\r\n    SELECT \r\n        \"transactionId\",\r\n        \"userId\",\r\n        amount,\r\n        location,\r\n        device,\r\n        merchant,\r\n        fraud_reason,\r\n        RANK() OVER (PARTITION BY \"userId\" ORDER BY amount DESC) AS fraud_rank\r\n    FROM transaction_predictions\r\n    WHERE prediction = 1\r\n) t\r\nWHERE fraud_rank <= 3;\r\n"
    }
   ]
  },
  {
   "title": "Transactions by device type",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT device, COUNT(*) AS transaction_count FROM transaction_predictions GROUP BY device ORDER BY transaction_count DESC;"
    }
   ]
  },
  {
   "title": "Fraud Amount Contribution by Merchant",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT merchant, SUM(amount) AS fraud_amount\r\nFROM transaction_predictions\r\nWHERE prediction = 1\r\nGROUP BY merchant\r\nORDER BY fraud_amount DESC;\r\n"
    }
   ]
  },
  {
   "title": "Prediction",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT prediction, COUNT(*) AS total_transactions FROM transaction_predictions GROUP BY prediction;"
    }
   ]
  },
  {
   "title": "Fraud reason Breakdown",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT fraud_reason, COUNT(*) AS count\r\nFROM transaction_predictions\r\nWHERE prediction = 1\r\nGROUP BY fraud_reason\r\nORDER BY count DESC;\r\n"
    }
   ]
  },
  {
   "title": "Average transaction amount for fraud vs normal",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT prediction, AVG(amount) AS avg_amount FROM transaction_predictions GROUP BY prediction;"
    }
   ]
  },
  {
   "title": "Fraud transactions by location",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT location, COUNT(*) AS fraud_count FROM transaction_predictions WHERE prediction = 1 GROUP BY location ORDER BY fraud_count DESC;"
    }
   ]
  }
 ]
}